# Generated by Django 3.0.2 on 2020-01-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(default='unknown', max_length=100)),
                ('arrival', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=1)),
                ('shared', models.BooleanField(default=False)),
            ],
        ),
    ]
