# Generated by Django 3.0.2 on 2020-01-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='status',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
