# Generated by Django 3.0.2 on 2020-01-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
