# Generated by Django 3.0.2 on 2020-01-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0003_delete_ride'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('arrival', models.TimeField()),
                ('number', models.IntegerField(default=0)),
                ('shared', models.BooleanField(default=False)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
