# Generated by Django 3.0.2 on 2020-01-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(default='open', max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='user',
            field=models.IntegerField(),
        ),
    ]
