# Generated by Django 3.0.2 on 2020-02-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_auto_20200130_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='id',
        ),
        migrations.AddField(
            model_name='ride',
            name='_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
