# Generated by Django 3.0.2 on 2020-02-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_auto_20200207_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
