# Generated by Django 3.0.2 on 2020-02-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_auto_20200207_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='_id',
        ),
        migrations.AddField(
            model_name='ride',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
