# Generated by Django 3.0.2 on 2020-02-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_auto_20200207_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
