# Generated by Django 3.0.2 on 2020-02-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_auto_20200207_1534'),
        ('rides', '0014_auto_20200207_1513'),
    ]

    operations = [
    ]
