# Generated by Django 3.0.2 on 2020-02-07 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('rides', '0016_auto_20200207_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('plate', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('passengers', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='ride',
            name='id',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
