# Generated by Django 3.0.2 on 2020-02-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_auto_20200207_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='sharer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.IntegerField(default=0),
        ),
    ]
