# Generated by Django 3.0.2 on 2020-02-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_auto_20200208_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='email',
            field=models.CharField(default='xxx@163.com', max_length=100),
        ),
    ]
